package net.nifheim.matrix.api.player;

import java.util.Date;
import java.util.UUID;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * @author Jaime Suárez
 */
public interface MatrixPlayer {

    /**
     * ObjectId of this user, it is a unique identifier that can be used to identify the user, it is generated by the
     * database, and it is not related to the {@link UUID} of the user.
     * <p>
     * It can be used to identify the user in the database, it is a 24 character long hexadecimal string.
     * </p>
     *
     * @return ObjectId of this user.
     * @see #getUniqueId()
     */
    String getId();

    /**
     * <p>
     * Get the minecraft {@link UUID} of this user, the {@link UUID#version()} method can be used to check if it is a
     * Mojang assigned {@link UUID} or a cracked {@link UUID}.
     * </p>
     * <p>
     * Premium players have version 4 {@link UUID}s, while cracked players have version 3 {@link UUID}s, they are
     * generated using the bytes of {@code "OfflinePlayer:" + name}.
     * </p>
     *
     * @return current {@link UUID} of this user.
     */
    @NotNull UUID getUniqueId();

    /**
     * Get the real name of this user.
     *
     * @return Saved Name of this user.
     */
    @NotNull String getName();

    @Nullable String getLowercaseName();

    /**
     * Get the displayed name of this user, this name is used in messages and chat.
     *
     * @return Saved display name of this user.
     */
    @NotNull String getDisplayName();

    boolean isPremium();

    boolean isRegistered();

    boolean isLoggedIn();

    @NotNull String getLastLocale();

    @Nullable Date getLastLogin();

    @NotNull Date getRegistration();
}
