name: Matrix-Bukkit
main: com.github.beelzebu.matrix.api.MatrixBukkitBootstrap
description: 'Network management plugin'
version: ${pluginVersion}
author: Beelzebu
softdepend: [ LuckPerms, PlaceholderAPI, Votifier ]
loadbefore: [ NetworkLevels ]
api-version: 1.15