name: Matrix-Bukkit
main: com.github.beelzebu.matrix.api.MatrixBukkitBootstrap
description: 'Network management plugin'
version: ${pluginVersion}
author: Beelzebu
depend: [ PlaceholderAPI ]
loadbefore: [ NetworkLevels ]
api-version: 1.16
provides: [ CommandLib, CoreUtils ]
libraries:
- 'com.github.ben-manes.caffeine:caffeine:3.1.1'
- 'org.slf4j:slf4j-api:1.7.32'
- 'org.slf4j:slf4j-nop:1.7.32'
- 'com.zaxxer:HikariCP:5.0.1'
- 'org.mariadb.jdbc:mariadb-java-client:2.7.3'
- 'org.apache.commons:commons-pool2:2.11.1'
- 'redis.clients:jedis:3.9.0'
- 'org.mongodb:bson:4.7.1'
- 'org.mongodb:mongodb-driver-core:4.7.1'
- 'org.mongodb:mongodb-driver-sync:4.7.1'
- 'dev.morphia.morphia:morphia-core:2.2.7'