package net.nifheim.matrix.api.server;

import java.util.Objects;
import org.jetbrains.annotations.NotNull;

/**
 * <p>Utility class used to generate server names implementing our server naming pattern, the name is generated in 3
 * parts, where only the first two parts are required and the third part is used for unique server names, if the {@link
 * ServerType} is equals to server group, then is omitted.</p>
 * <ol>
 *     <li>{@link ServerType} (required)</li>
 *     <li>Server group name (required but may be omitted during name generation)</li>
 *     <li>Server name or number generated by the implementation</li>
 * </ol>
 * <p>Every part except the number is separated using {@link #SEPARATOR} character.</p>
 * <p>Names are generated in the following format</p>
 * <code>group(:servertype)?(:name|id)</code>
 * <p>Where the {@link ServerType} will be omitted if is equals to the group and the name or id.</p>
 *
 * <table border="1">
 *     <caption>Unnamed server examples</caption>
 *     <tr>
 *         <th>Data</th>
 *         <th>Generated names</th>
 *     </tr>
 *     <tr>
 *         <td>
 *             <ul>
 *                 <li>Type: {@link ServerType#LOBBY}</li>
 *                 <li>Group: lobby</li>
 *             </ul>
 *         </td>
 *         <td>
 *             <ul>
 *                 <li>lobby1</li>
 *                 <li>lobby2</li>
 *                 <li>lobby3</li>
 *             </ul>
 *         </td>
 *     </tr>
 *     <tr>
 *         <td>
 *             <ul>
 *                 <li>Type: {@link ServerType#LOBBY}</li>
 *                 <li>Group: skywars</li>
 *             </ul>
 *         </td>
 *         <td>
 *             <ul>
 *                 <li>skywars:lobby1</li>
 *                 <li>skywars:lobby2</li>
 *                 <li>skywars:lobby3</li>
 *             </ul>
 *         </td>
 *     </tr>
 *     <tr>
 *         <td>
 *             <ul>
 *                 <li>Type: {@link ServerType#ARENA}</li>
 *                 <li>Group: skywars</li>
 *             </ul>
 *         </td>
 *         <td>
 *             <ul>
 *                 <li>skywars:arena1</li>
 *                 <li>skywars:arena2</li>
 *                 <li>skywars:arena3</li>
 *             </ul>
 *         </td>
 *     </tr>
 * </table>
 * <table border="1">
 *     <caption>Named server examples</caption>
 *     <tr>
 *         <th>Data</th>
 *         <th>Generated name</th>
 *     </tr>
 *     <tr>
 *         <td>
 *             <ul>
 *                 <li>Type: {@link ServerType#SURVIVAL}</li>
 *                 <li>Group: survival</li>
 *                 <li>Name: magenta</li>
 *             </ul>
 *         </td>
 *         <td>survival:magenta</td>
 *     </tr>
 *     <tr>
 *         <td>
 *             <ul>
 *                 <li>Type: {@link ServerType#SURVIVAL}</li>
 *                 <li>Group: survival</li>
 *                 <li>Name: red</li>
 *             </ul>
 *         </td>
 *         <td>survival:red</td>
 *     </tr>
 *     <tr>
 *         <td>
 *             <ul>
 *                 <li>Type: {@link ServerType#SURVIVAL}</li>
 *                 <li>Group: guilds</li>
 *                 <li>Name: green</li>
 *             </ul>
 *         </td>
 *         <td>guilds:survival:red</td>
 *     </tr>
 * </table>
 *
 * @author Jaime Suárez
 */
public final class ServerName {

    /**
     * Character used to separate group, {@link ServerType} and name in the same string.
     */
    public static final char SEPARATOR = ':';

    /**
     * Generate a named server name using the {@link ServerType}, group name and server name as unique identifier.
     *
     * @param serverType {@link ServerType} for the server.
     * @param group      name of the server group.
     * @param name       name used as unique identifier for this server.
     * @return Generated server name using the provided information.
     */
    public static String of(@NotNull String group, @NotNull ServerType serverType, @NotNull String name) {
        StringBuilder builder = prefix(group, serverType);
        Objects.requireNonNull(name, "name");
        builder.append(SEPARATOR).append(name);
        return builder.toString().toLowerCase();
    }

    /**
     * Generate a named server name using the {@link ServerType}, group name and server name as unique identifier.
     *
     * @param serverType {@link ServerType} for the server.
     * @param group      name of the server group.
     * @param uid        numeric unique identifier for this server.
     * @return Generated server name using the provided information.
     */
    public static String of(@NotNull String group, @NotNull ServerType serverType, int uid) {
        StringBuilder builder = prefix(group, serverType);
        builder.append(uid);
        return builder.toString().toLowerCase();
    }

    /**
     * Generate a {@link StringBuilder} with the prefix for the server name using the {@link ServerType} and group name.
     *
     * @param group      name of the server group.
     * @param serverType {@link ServerType} for the server.
     * @return {@link StringBuilder} with the prefix for the server name to be used for generating a server name.
     */
    public static StringBuilder prefix(@NotNull String group, @NotNull ServerType serverType) {
        Objects.requireNonNull(group, "group");
        Objects.requireNonNull(serverType, "serverType");
        StringBuilder builder = new StringBuilder(group);
        if (!Objects.equals(group, serverType.toString())) {
            builder.append(SEPARATOR).append(serverType);
        }
        return builder;
    }
}
