name: Matrix-Bukkit
main: io.github.beelzebu.matrix.MatrixBukkitBootstrap
version: ${project.version}
author: Beelzebu
softdepend: [PlaceholderAPI, Votifier, Essentials, LuckPerms, WorldGuard, NametagEdit]