name: Matrix-Bukkit
main: com.github.beelzebu.matrix.MatrixBukkitBootstrap
description: 'Network management plugin'
version: ${pluginVersion}
author: Beelzebu
depend: [LuckPerms, Coins, PlaceholderAPI]
softdepend: [Votifier]
loadbefore: [NetworkLevels]
api-version: 1.15